name: Naukri Job Bot

permissions:
  contents: write

on:
  schedule:
    - cron: "30 3 * * *"
    - cron: "30 8 * * *"
    - cron: "30 11 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install node modules
        run: npm install

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Run bot
        run: node scripts/sendJobs.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit updated jobs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/sentJobs.json
          git commit -m "update sent jobs" || echo "No changes"
          git push
